-- MySQL Script generated by MySQL Workbench
-- Mon Jun 28 02:02:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema upvote_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema upvote_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upvote_app` DEFAULT CHARACTER SET latin1 ;
USE `upvote_app` ;

-- -----------------------------------------------------
-- Table `upvote_app`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upvote_app`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(140) NOT NULL,
  `expiration_date_time` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `upvote_app`.`choices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upvote_app`.`choices` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(40) NOT NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_choices_post_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_choices_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `upvote_app`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `upvote_app`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upvote_app`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` ENUM('ROLE_USER', 'ROLE_ADMIN') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `upvote_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upvote_app`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `upvote_app`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upvote_app`.`user_roles` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_roles_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_roles_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `upvote_app`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `upvote_app`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `upvote_app`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upvote_app`.`votes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `choice_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_votes_post_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_votes_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_votes_choice_idx` (`choice_id` ASC) VISIBLE,
  CONSTRAINT `fk_votes_choices1`
    FOREIGN KEY (`choice_id`)
    REFERENCES `upvote_app`.`choices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `upvote_app`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `upvote_app`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
